### PR TITLE
Fix Issue 29 "scan with support of batch/startTime/endTime options"

### PR DESCRIPTION
**Pull request by yellowbrickc**
Hi,

I'm back with a new pull request. Can you please review it?
Thanks,
Krisztina

### CODE REVIEW

**Comment by wdavidw** [comment]
Sounds good, do u need a new release ?

**Comment by yellowbrickc** [comment]
Yes. This time would be great :)

**Comment by yellowbrickc** [comment]
And you could close Issue 29, I just took his code, implemented it as coffee script and prove it with some tests

**Comment by wdavidw** [comment]
thanks, package is published

**Pull request merged**
